export const FETCH_FOOD = 'FETCH_FOOD';
export const FOOD_START = 'FOOD_START';
export const FOOD_SUCCESS = 'FOOD_SUCCESS';
export const FOOD_FAIL = 'FOOD_FAIL';
export const FOOD_LIMITED_SUCCESS = 'FOOD_LIMITED_SUCCESS';
export const FOOD_DATA_ADD = 'FOOD_DATA_ADD';
export const FOOD_DATA_UPDATE = 'FOOD_DATA_UPDATE';
export const FOOD_DATA_DELETE_ELEMENT = 'FOOD_DATA_DELETE_ELEMENT';

export const FOOD_COMPARE_DATA_UPDATE = 'FOOD_COMPARE_DATA_UPDATE';

export const PRODUCT_ADD_TO_CART_DATA = 'PRODUCT_ADD_TO_CART_DATA';
export const PRODUCT_REMOVE_FROM_CART_DATA = 'PRODUCT_REMOVE_FROM_CART_DATA,';
export const PRODUCT_UPDATE_IN_CART_DATA = 'UPDATE_FOOD_IN_CART_DATA';

export const  AUTH_START = 'AUTH_START ';
export const  AUTH_SUCCESS = 'AUTH_SUCCESS';
export const  AUTH_FAIL = 'AUTH_FAIL';
export const  AUTH_LOGOUT = 'AUTH_LOGOUT';