export const  AUTH_START = 'AUTH_START ';
export const  AUTH_SUCCESS = 'AUTH_SUCCESS';
export const  AUTH_FAIL = 'AUTH_FAIL';
export const  AUTH_LOGOUT = 'AUTH_LOGOUT';

export const  EMAIL_UPDATE = 'EMAIL_UPDATE';
export const  EMAIL_ADD = 'EMAIL_ADD';
export const  EMAIL_REMOVE = 'EMAIL_REMOVE';
export const  EMAIL_GET = 'EMAIL_GET';
export const  EMAIL_LIST = 'EMAIL_LIST';
export const  EMAIL_CURRENT_SELECTED_UPDATE = 'EMAIL_CURRENT_SELECTED_UPDATE';
export const  EMAIL_SEND_MESSAGE_FORM_STATUS_UPDATE = 'EMAIL_SEND_MESSAGE_FORM_STATUS_UPDATE';
export const  EMAIL_UPDATE_SEARCH_PARAMS = 'EMAIL_UPDATE_SEARCH_PARAMS';